source 'https://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'jquery-rails'
gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails' #,  '~> 3.2.3'
  gem 'coffee-rails' #, '#~> 3.2.1'
  gem "therubyracer"
  gem 'libv8', '~> 3.11.8'
  gem "less-rails" 
  gem 'uglifier', '>= 1.0.3'
end

gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'haml-rails'
gem 'rabl'
gem 'simple_form'
gem 'crummy'
#gem "coffee-filter"
gem 'recursive_open_struct', :git => "git://github.com/awesome/recursive_open_struct.git"

#
# optional
#
# http://thechangelog.com/post/21217781637/quiet-assets-silence-asset-pipeline-messages
gem 'quiet_assets', :group => :development
