---
6:
  id: 6
  name: activate_to_confirm
  cancel_url: ''
  element: stepre
  redirect_to: ''
  steps_count: 1
  attrs_count: 1
  nav: false
  first_step_id: 15
  last_step_id: 15
  created_at: 2012-12-12 21:25:59.555053000 Z
  updated_at: 2012-12-12 21:35:56.233462000 Z
  steps:
    15:
      id: 15
      form_id: 6
      name: activate
      template: confirmations/steps/activate.html.haml
      prev_step_id: 
      next_step_id: 
      position: 0
      attrs_count: 1
      nav_step: 
      nav_step_name: 
      signin_required: false
      before_snippet: ''
      after_snippet: ! "if obj.valid\r\n  unless confirmation = Confirmation.find(merged_hash[\"confirmation_uuid\"])\r\n
        \   obj.valid = false\r\n    obj.json = {:base => [\"Invalid Confirmation
        ID: #{merged_hash['confirmation_uuid']}\"]}.to_json\r\n    return obj\r\n
        \ end\r\n\r\n  unless user = User.find(merged_hash[\"user_uuid\"])\r\n    obj.valid
        = false\r\n    obj.json = {:base => [\"Invalid User ID: #{merged_hash['user_uuid']}\"]}.to_json\r\n
        \   return obj\r\n  end\r\n\r\n  confirmation.user_userid = user.user_userid\r\n
        \ if confirmation.confirm!\r\n    flash_hash = {:flash => \"success\", :message
        => \"Successfully activated license.\"}\r\n    local_redirect_hash = {:host
        => \"localhost:3000\", :only_path => true, :company_uuid => merged_hash[\"company_uuid\"],
        :form_data => Stepre::Form.write_form_data(flash_hash)}\r\n    merged_hash[:redirect_to]
        = Rails.application.routes.url_helpers.dashboard_url(local_redirect_hash)\r\n
        \ else\r\n    obj.valid = false\r\n    obj.json = {:base => [\"Error activating
        license.\"]}.to_json\r\n    return obj\r\n  end\r\nend"
      created_at: 2012-12-12 21:26:26.114653000 Z
      updated_at: 2012-12-12 21:46:56.694508000 Z
      attrs:
        46:
          id: 46
          name: accepts
          display_name: By checking this box you are agreeing to the terms and conditions
            above.
          step_id: 15
          reck: 'false'
          form_id: 6
          element: input
          created_at: 2012-12-12 21:35:19.067665000 Z
          updated_at: 2012-12-12 21:35:19.067665000 Z
          validations:
            15:
              id: 15
              name: validates_presence_of TOS
              desc: TOS checkbox validation
              snippet: validates_presence_of :ATTR, :message => "must be checked"
              created_at: 2012-12-11 23:30:39.122181000 Z
              updated_at: 2012-12-11 23:31:34.667607000 Z
