---
7:
  id: 7
  name: office365
  cancel_url: ''
  element: office365
  redirect_to: ''
  steps_count: 3
  attrs_count: 0
  nav: false
  first_step_id: 16
  last_step_id: 16
  created_at: 2013-01-04 20:24:59.802019000 Z
  updated_at: 2013-01-04 20:31:15.160698000 Z
  steps:
    16:
      id: 16
      form_id: 7
      name: start
      template: office365/steps/start
      prev_step_id: 
      next_step_id: 17
      position: 1
      attrs_count: 
      nav_step: 
      nav_step_name: 
      signin_required: false
      before_snippet: ''
      after_snippet: ''
      created_at: 2013-01-04 20:28:11.836217000 Z
      updated_at: 2013-01-05 00:32:50.523254000 Z
      attrs: {}
    17:
      id: 17
      form_id: 7
      name: user_account
      template: office365/steps/user_account
      prev_step_id: 16
      next_step_id: 18
      position: 2
      attrs_count: 
      nav_step: 
      nav_step_name: 
      signin_required: false
      before_snippet: ''
      after_snippet: ''
      created_at: 2013-01-05 00:30:18.798629000 Z
      updated_at: 2013-01-05 00:33:04.054418000 Z
      attrs: {}
    18:
      id: 18
      form_id: 7
      name: payment
      template: office365/steps_custom/accumulus_iframe
      prev_step_id: 17
      next_step_id: 
      position: 3
      attrs_count: 
      nav_step: 
      nav_step_name: 
      signin_required: false
      before_snippet: ''
      after_snippet: ''
      created_at: 2013-01-05 00:32:27.276866000 Z
      updated_at: 2013-01-05 00:33:40.873799000 Z
      attrs: {}
